controllers/add_electricity.py
from flask import render_template, flash, redirect, url_for
from flask_login import current_user

from controllers import _Controller
from models import Electricity


class AddElectricityController(_Controller):
    template = 'add_electricity.html'

    def _post(self):
        total_kilowatts = self.request_data.get('total_kilowatts')
        amount_per_kilowatt = self.request_data.get('amount_per_kilowatt')
        user = current_user

        Electricity.create(total_kilowatts=total_kilowatts, amount_per_kilowatt=amount_per_kilowatt, user=user)

        flash("Електроенергії додано вдачно")

        return redirect(url_for("main.profile"))

    def _get(self):
        return render_template(self.template)

controllers/add_lot.py
from flask import render_template, flash, redirect, url_for
from flask_login import current_user

from constants import LotStatuses
from controllers import _Controller
from models import Lot, Electricity, db


class AddLotController(_Controller):
    template = 'add_lot.html'

    def _post(self):
        amount_per_kilowatt = round(float(self.request_data.get('amount_per_kilowatt', 0)), 8)
        company_name = self.request_data.get('company_name')
        electricity_id = self.request_data.get('electricity_id')
        kilowatts_number = float(self.request_data.get('kilowatts_number', 0))

        electricity = Electricity.select().where(Electricity.id == int(electricity_id)).first()

        if electricity.total_kilowatts < kilowatts_number:
            flash("Number of kilowatts bigger total kilowatt count")
            return redirect(url_for("main.profile"))

        Lot.create(
            status=LotStatuses.New,
            amount_per_kilowatt=amount_per_kilowatt,
            salesman=current_user,
            company_name=company_name,
            electricity=electricity,
            kilowatts_number=kilowatts_number,
        )

        with db.atomic():
            electricity.total_kilowatts_freeze = kilowatts_number
            electricity.total_kilowatts = electricity.total_kilowatts - electricity.total_kilowatts_freeze
            electricity.save()

        flash("Successful create trading lot")

        return redirect(url_for("main.profile"))

    def _get(self):
        electricities = list(Electricity.select().where(Electricity.user == current_user))

        if len(electricities) == 0:
            flash("Need create electricity")
            return redirect(url_for("main.profile"))
        
        return render_template(self.template, electricities=electricities)

controllers/buy_electricity.py
from flask import render_template, flash, redirect, url_for
from flask_login import current_user
from utils import additional_order_kilowatts

from controllers import _Controller
from models import User

class BuyElectricityController(_Controller):
    template = 'buy_electricity.html'

    def _post(self):
        total_kilowatts = int(self.request_data.get('total_kilowatts'))
        agregator = User.select().where(User.id == current_user).first()
        additional_order_kilowatts(total_kilowatts, agregator)

        return redirect(url_for("main.profile"))

    def _get(self):
        return render_template(self.template)

controllers/buy_lot.py
from flask import render_template, flash, redirect, url_for
from flask_login import current_user

from constants import LotStatuses
from controllers import _Controller
from eth import EthProtocol
from models import Lot, Electricity, db


class BuyLotController(_Controller):
    template = "buy_lot.html"

    def _post(self, lot_id):
        eth_protocol = EthProtocol()

        kilowatts_number = float(self.request_data.get('kilowatts_number', 0))
        lot = Lot.select().where(Lot.id == int(lot_id)).first()
        electricity = lot.electricity

        if kilowatts_number > lot.kilowatts_number:
            flash("Input number so biggest")
            return redirect(url_for('main.electricity_market'))

        wallet_balance = eth_protocol.get_balance(current_user.wallet)

        lot_amount = round(lot.amount_per_kilowatt * kilowatts_number, 8)

        if wallet_balance < lot_amount:
            flash("Amount bigger wallet balance")
            return redirect(url_for('main.electricity_market'))

        with db.atomic():
            lot.kilowatts_number -= kilowatts_number
            if lot.kilowatts_number == 0:
                lot.status = LotStatuses.Success

            electricity.total_kilowatts_freeze -= kilowatts_number
            electricity.save()

            tx_hash = eth_protocol.send_eth_transaction(current_user.wallet, current_user.wallet.password, lot.aggregator.wallet.address, lot_amount)
            lot.transactions_history[tx_hash] = kilowatts_number
            lot.save()

            Electricity.create(user=current_user, electricity_type=lot.electricity.electricity_type, total_kilowatts=kilowatts_number)

        flash("Successful buy lot")

        return redirect(url_for("main.profile"))

    def _get(self, lot_id):
        lot = Lot.select().where(Lot.id == int(lot_id)).first()
        return render_template(self.template, lot=lot)

controllers/edit_electricity.py
from flask import render_template, flash, redirect, url_for

from controllers import _Controller
from models import Electricity


class EditElectricityController(_Controller):
    template = 'edit_electricity.html'

    def _post(self, electricity_id):
        electricity = Electricity.select().where(Electricity.id == int(electricity_id)).first()

        electricity.electricity_type = self.request_data.get("electricity_type")
        electricity.total_kilowatts = self.request_data.get("total_kilowatts")
        electricity.save()

        flash("Successful edit electricity")

        return redirect(url_for("main.profile"))

    def _get(self, electricity_id):
        electricity = Electricity.select().where(Electricity.id == int(electricity_id)).first()
        return render_template(self.template, electricity=electricity)

controllers/edit_lot.py
from flask import render_template, flash, redirect, url_for

from controllers import _Controller
from models import Lot


class EditLotController(_Controller):
    template = 'edit_lot.html'

    def _post(self, lot_id):
        lot = Lot.select().where(Lot.id == int(lot_id)).first()

        lot.amount_per_kilowatt = self.request_data.get("amount_per_kilowatt")
        lot.company_name = self.request_data.get("company_name")
        lot.save()

        flash("Successful edit lot")

        return redirect(url_for("main.profile"))

    def _get(self, lot_id):
        lot = Lot.select().where(Lot.id == int(lot_id)).first()
        return render_template(self.template, lot=lot)

controllers/edit_wallet.py
from flask import render_template, flash, redirect, url_for
from flask_login import current_user

from controllers import _Controller
from eth import EthProtocol


class EditWalletController(_Controller):
    template = 'edit_wallet.html'

    def _post(self):
        amount = round(float(self.request_data.get("amount", 0)), 8)

        current_user.wallet.balance += amount
        current_user.wallet.save()

        flash("Баланс вдачно поповнено")

        return redirect(url_for("main.profile"))

    def _get(self):
        return render_template(self.template)

controllers/login.py
from flask import render_template, flash, redirect, url_for
from flask_login import login_user
from werkzeug.security import check_password_hash

from controllers import _Controller
from models import User


class LoginController(_Controller):
    template = 'login.html'

    def _post(self):
        email = self.request_data.get('email')
        password = self.request_data.get('password')
        remember = True if self.request_data.get('remember') else False

        user = User.select().where(User.email == email).first()

        if not user or not check_password_hash(user.password, password):
            flash('Please check your login details and try again.')
            return redirect(url_for('main.login'))

        login_user(user, remember=remember)

        return redirect(url_for('main.profile'))

    def _get(self):
        return render_template(self.template)

controllers/signup.py
from flask import render_template, flash, url_for, redirect
from werkzeug.security import generate_password_hash

from constants import AccountType, STATIONS
from controllers import _Controller
from eth import EthProtocol
from models import User

account_types = {"User": AccountType.User, "Salesman": AccountType.Salesman, "Aggregator": AccountType.Aggregator, "ForeignUser": AccountType.ForeignUser}


class SignUpController(_Controller):
    template = 'signup.html'

    def _post(self):
        email = self.request_data.get("email")
        name = self.request_data.get("name")
        password = self.request_data.get("password")
        account_type = account_types[self.request_data.get("account_type")]
        address = self.request_data.get("address")
        post_index = self.request_data.get("post_index")
        aggregator_id = self.request_data.get("aggregators")
        country = self.request_data.get("country")
        station = self.request_data.get("station")

        addons = dict(address=address, post_index=post_index, aggregator_id=aggregator_id, country=country,
                      station=station)

        user = User.get_or_none(User.email == email)

        if user is None:
            eth_protocol = EthProtocol()

            wallet = eth_protocol.create_wallet()

            User.create(
                email=email,
                name=name,
                password=generate_password_hash(password, method='sha256'),
                account_type=account_type,
                wallet=wallet,
                addons=addons
            )

            flash('Successful create account')
        else:
            flash('Email address already exists')
            return redirect(url_for("main.signup"))

        return redirect(url_for("main.login"))

    def _get(self):
        aggregators = list(User.select().where(User.account_type == AccountType.Aggregator))
        return render_template(self.template, aggregators=aggregators, stations=STATIONS)

views.py
from flask import request, Blueprint, render_template
from flask_login import login_required
from flask_paginate import get_page_parameter, Pagination

from controllers.add_electricity import AddElectricityController
from controllers.add_lot import AddLotController
from controllers.buy_lot import BuyLotController
from controllers.delete_electricity import DeleteElectricityController
from controllers.delete_lot import DeleteLotController
from controllers.edit_coefficient import EditUserCoefficientController, \
    EditForeignUserCoefficientController,\
    EditUserLimitCoefficientController,\
    EditMinReserveCoefficientController, \
    EditUserSalePriorithyController,\
    EditUserBuyPriorithyController
from controllers.edit_electricity import EditElectricityController
from controllers.edit_lot import EditLotController
from controllers.edit_wallet import EditWalletController
from controllers.electricity_market import ElectricityMarketController
from controllers.indication import IndicationController
from controllers.login import LoginController
from controllers.logout import LogoutController
from controllers.profile import ProfileController
from controllers.signup import SignUpController
from controllers.buy_electricity import BuyElectricityController
from controllers.view_electricity import ViewElectricityController
from models import Lot

blueprint = Blueprint('main', __name__)


@blueprint.route("/market", methods=["GET"])
@login_required
def electricity_market():
    return ElectricityMarketController(request).call()


@blueprint.route("/add_lot", methods=["GET", "POST"])
@login_required
def add_lot():
    return AddLotController(request).call()


@blueprint.route("/buy_lot/<lot_id>", methods=["GET", "POST"])
@login_required
def buy_lot(lot_id):
    return BuyLotController(request).call(lot_id)


@blueprint.route("/edit_lot/<lot_id>", methods=["GET", "POST"])
@login_required
def edit_lot(lot_id):
    return EditLotController(request).call(lot_id)


@blueprint.route("/delete_lot/<lot_id>", methods=["POST"])
@login_required
def delete_lot(lot_id):
    return DeleteLotController(request).call(lot_id)


@blueprint.route("/add_electricity", methods=["GET", "POST"])
@login_required
def add_electricity():
    return AddElectricityController(request).call()


@blueprint.route("/edit_electricity/<electricity_id>", methods=["GET", "POST"])
@login_required
def edit_electricity(electricity_id):
    return EditElectricityController(request).call(electricity_id)


@blueprint.route("/delete_electricity/<electricity_id>", methods=["POST"])
@login_required
def delete_electricity(electricity_id):
    return DeleteElectricityController(request).call(electricity_id)


@blueprint.route("/", methods=["GET"])
@blueprint.route("/profile", methods=["GET"])
@login_required
def profile():
    return ProfileController(request).call()


@blueprint.route("/logout", methods=["GET"])
def logout():
    return LogoutController(request).call()


@blueprint.route("/login", methods=['GET', 'POST'])
def login():
    return LoginController(request).call()


@blueprint.route("/signup", methods=['GET', 'POST'])
def signup():
    return SignUpController(request).call()


@blueprint.route("/indication/<aggregator_id>/<user_id>", methods=["POST"])
def indication(aggregator_id, user_id):
    return IndicationController(request).call(aggregator_id, user_id)


@blueprint.route("/edit_wallet", methods=["POST", "GET"])
def edit_wallet():
    return EditWalletController(request).call()


@blueprint.route("/edit_user_sale_coefficient", methods=["POST", "GET"])
def edit_user_sale_coefficient():
    return EditUserCoefficientController(request).call()


@blueprint.route("/edit_user_buy_coefficient", methods=["POST", "GET"])
def edit_user_buy_coefficient():
    return EditForeignUserCoefficientController(request).call()


@blueprint.route("/edit_user_limit_coefficient", methods=["POST", "GET"])
def edit_user_limit_coefficient():
    return EditUserLimitCoefficientController(request).call()


@blueprint.route("/edit_min_reserve_coefficient", methods=["POST", "GET"])
def edit_min_reserve_coefficient():
    return EditMinReserveCoefficientController(request).call()


@blueprint.route("/edit_user_sale_priority", methods=["POST", "GET"])
def edit_user_sale_priority():
    return EditUserSalePriorithyController(request).call()


@blueprint.route("/edit_user_buy_priority", methods=["POST", "GET"])
def edit_user_buy_priority():
    return EditUserBuyPriorithyController(request).call()


@blueprint.route("/lots/<status>", methods=["POST", "GET"])
@blueprint.route("/lots", methods=["POST", "GET"])
def lots(status=None):
    page = int(request.args.get('page', 1))
    per_page = 10
    offset = (page - 1) * per_page

    lots = Lot.select()
    if status is not None:
        lots = lots.where(Lot.status == status)
    lots = lots.order_by(Lot.id.desc())
    lots_for_render = lots.limit(per_page).offset(offset)

    search = False

    q = request.args.get('q')
    if q:
        search = True

    pagination = Pagination(page=page, per_page=per_page, offset=offset,
                           total=lots.count(), css_framework='bulma',
                           search=search)

    return render_template('lots.html', lots=lots_for_render, pagination=pagination)


@blueprint.route("/buy_electricity", methods=["GET", "POST"])
@login_required
def buy_electricity():
    # todo покупка создать лот
    return BuyElectricityController(request).call()


@blueprint.route("/view_electricity", methods=["GET", "POST"])
@login_required
def view_electricity():
    return ViewElectricityController(request).call()

templates/add_electricity.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Додати електроенергію для продажу</h3>
    <div class="box">
        <form method="POST" action="/add_electricity">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" step="0.01" name="total_kilowatts" placeholder="Кількість електроенергії" autofocus="" required>
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" step="0.01" name="amount_per_kilowatt" placeholder="Ціна за кіловат енергії" required>
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Додати електроенергію</button>
        </form>
    </div>
</div>
{% endblock %}

templates/add_lot.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Add lot</h3>
    <div class="box">
        <form method="POST" action="/add_lot">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" step="0.01" name="amount_per_kilowatt" placeholder="Amount per kilowatt" autofocus="" required>
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="company_name" placeholder="Company name" required>
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <div class="select">
                      <select name="electricity_id" required>
                        {% for electricity in electricities %}
                            <option value="{{ electricity }}">Type: {{ electricity.electricity_type }}, total free kilowatts: {{ electricity.total_kilowatts }}, freeze kilowatt: {{ electricity.total_kilowatts_freeze }}</option>
                        {% endfor %}
                      </select>
                    </div>
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" step="0.01" name="kilowatts_number" placeholder="Number of kilowatts" autofocus="" required>
                </div>
            </div>


            <button class="button is-block is-info is-large is-fullwidth">Add trading lot</button>
        </form>
    </div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Auth Example</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
</head>

<body>
    <section class="hero is-primary is-fullheight">

        <div class="hero-head">
            <nav class="navbar">
                <div class="container">

                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            {% if current_user.is_authenticated %}
                                <a href="{{ url_for('main.profile') }}" class="navbar-item">
                                    {{ current_user.name }}
                                </a>
                            {% endif %}
                            {% if not current_user.is_authenticated %}
                            <a href="{{ url_for('main.login') }}" class="navbar-item">
                                Login
                            </a>
                            <a href="{{ url_for('main.signup') }}" class="navbar-item">
                                Sign Up
                            </a>
                            {% endif %}
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('main.logout') }}" class="navbar-item">
                                Logout
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        <div class="notification is-danger">
                            {{ messages[0] }}
                        </div>
                    {% endif %}
                {% endwith %}
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>
</body>
</html>

templates/edit_foreign_user_coefficient.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Поповнення рахунку</h3>
    <div class="box">
        <form method="POST" action="/edit_foreign_user_coefficient">
            <div class="field">
                <label for="buy_local">Користувач</label>
                <div class="control">
                    <input class="input is-large" id="buy_local" type="number" step="0.01" name="coefficient"
                           placeholder="Коефіціент" autofocus="" required value="{{ coefficient }}">
                </div>
            </div>

            <div class="field">
                <label for="buy_foregin">Іноземний користувач</label>
                <div class="control">
                    <input class="input is-large" id="buy_foregin" type="number" step="0.01" name="coefficient"
                           placeholder="Коефіціент" autofocus="" required value="{{ coefficient }}">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Змінити коефіціент</button>
        </form>
    </div>
</div>
{% endblock %}

templates/edit_min_reserve_coefficient.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Резерв зберігання електроенергії</h3>
    <div class="box">
        <form method="POST" action="/edit_min_reserve_coefficient">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" step="100" name="coefficient"
                           placeholder="Коефіціент" autofocus="" required value="{{ coefficient }}">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Змінити резерв</button>
        </form>
    </div>
</div>
{% endblock %}

templates/edit_user_buy_priority.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Оберіть пріорітет купівлі</h3>
    <div class="box">
        <form method="POST" action="/edit_user_buy_priority">

            <div class="field">
                <div class="control">
                    <label for="buy_priority_1" style="padding: 5px 0 0 0; display: inline-block">1</label>
                    <div class="select">
                        <select name="buy_priority_1" required>
                            {% for value in values %}
                                <option value="{{ value }}" {% if coefficient[0] == value %}selected{% endif %}>{{ values[value]}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <label for="buy_priority_2" style="padding: 5px 0 0 0; display: inline-block">2</label>
                    <div class="select">
                        <select name="buy_priority_2" required>
                            {% for value in values %}
                                <option value="{{ value }}" {% if coefficient[1] == value %}selected{% endif %}>{{ values[value]}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <label for="buy_priority_3" style="padding: 5px 0 0 0; display: inline-block">3</label>
                    <div class="select">
                        <select name="buy_priority_3" required>
                            {% for value in values %}
                                <option value="{{ value }}" {% if coefficient[2] == value %}selected{% endif %}>{{ values[value]}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Змінити коефіціент</button>
        </form>
    </div>
</div>
{% endblock %}

templates/edit_user_coefficient.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Коефіціент продажу</h3>
    <div class="box">
        <form method="POST" action="/edit_user_coefficient">
            <div class="field">
                <label for="sale_local">Користувач</label>
                <div class="control">
                    <input id = "sale_local" class="input is-large" type="number" step="0.01" name="coefficient"
                           placeholder="Коефіціент" autofocus="" required value="{{ coefficient }}">
                </div>
            </div>

            <div class="field">
                <label for="sale_foregin">Іноземний користувач</label>
                <div class="control">
                    <input id = "sale_foregin" class="input is-large" type="number" step="0.01" name="coefficient"
                           placeholder="Коефіціент" autofocus="" required value="{{ coefficient }}">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Змінити коефіціент</button>
        </form>
    </div>
</div>
{% endblock %}

templates/edit_user_limit_coefficient.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Ліміту зберігання електроенергії</h3>
    <div class="box">
        <form method="POST" action="/edit_user_limit_coefficient">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" step="100" name="coefficient"
                           placeholder="Коефіціент" autofocus="" required value="{{ coefficient }}">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Змінити ліміт</button>
        </form>
    </div>
</div>
{% endblock %}

templates/electricitie_base.html
{{ pagination_e.info }}
{{ pagination_e.links }}
<div class="box">
    <table class="table is-fullwidth">
        <thead>
        <tr>
            <th>#</th>
            <th>Користувач</th>
            <th>Кількість кіловатів</th>
            <th>Ціна за кіловат</th>
        </tr>
        </thead>
        <tbody>
        {% if electricitys|length > 0 %}
            {% for electricity in electricitys %}
                <tr>
                    <td>{{ loop.index + pagination_e.skip }}</td>
                    <th>{{ electricity.user.name }}</th>
                    <td>{{ electricity.kilowatts }}</td>
                    <td>{{ electricity.amount }}</td>
                </tr>
            {% endfor %}
        {% else %}
            <tr><th>Наразі відсутні</th></tr>
        {% endif %}
        </tbody>
    </table>
</div>
{{ pagination_e.links }}

templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Login</h3>
    <div class="box">
        <form method="POST" action="/login">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Password">
                </div>
            </div>
            <div class="field">
                <label class="checkbox">
                    <input type="checkbox">
                    Remember me
                </label>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Login</button>
        </form>
    </div>
</div>
{% endblock %}

templates/lots_base.html
{{ pagination.info }}
{{ pagination.links }}
<div class="box">
    <table class="table is-fullwidth">
        <thead>
        <tr>
            <th>#</th>
            <th>Статус</th>
            <th>Ціна за кіловат</th>
            <th>Кількість кіловатів</th>
            <th>Сума</th>
            <th>Купівля/Продаж</th>
        </tr>
        </thead>
        <tbody>
        {% if lots|length > 0 %}
            {% for lot in lots %}

                <tr>
                    <td>{{ loop.index + pagination.skip }}</td>
                    <th>{{ lot.status|lot_status }}</th>
                    <td>{{ lot.average_price }}</td>
                    <td>{{ lot.kilowatts_number }}</td>
                    <td>{{ lot.average_price * lot.kilowatts_number }}</td>
                    <td>{{ lot.operation_type }}</td>
                </tr>

            {% endfor %}
        {% else %}
            <tr><th>Наразі відсутні</th></tr>
        {% endif %}
        </tbody>
    </table>
</div>
{{ pagination.links }}

templates/profile_salesman.html
{% extends "base.html" %}

{% block content %}
    <div class="columns is-multiline is-mobile">
        <div class="column">
            <h3 class="title">Гаманець</h3>
            <div class="box">
                <p>Баланс: {{ current_user.wallet.balance }}</p>
                <a class="button is-success is-rounded is-small" href="{{ url_for('main.edit_wallet') }}">Поповнити баланс</a>
            </div>
        </div>

        <div class="column">
            <h3 class="title">Ліміт зберігання електроенергії</h3>
            <div class="box">
                <p>Ліміт: {{ user_limit }}</p>
                <a class="button is-success is-rounded is-small" href="{{ url_for('main.edit_user_limit_coefficient') }}">Змінити ліміт</a>
            </div>
        </div>

        <div class="column">
            <h3 class="title">Пропозиції на ринку</h3>
            <div class="box">
                <a class="button is-success is-rounded" href="{{ url_for('main.view_electricity') }}">Переглянути пропозицій</a>
            </div>
        </div>
    </div>
    {% include 'lots_base.html' %}
{% endblock %}

templates/view_electricitie.html
{% extends "base.html" %}

{% block content %}
    {% include 'electricitie_base.html' %}
{% endblock %}